export const apiRoutes = {
  aboutUs: "/aboutus",
  report: "/report",
  user: "/user",
  userLog: "/user-time-log",
  userLoginGenerate: "/user/generate/login-user",
  crops: "/crops",
  products: "/product",
  productsIManager: "/product/internet-shop",
  collection: "/collection/remaining-collections",
  collectionProducts: "/collection/remaining-products",
  collectionPrice: "/collection-prices",
  collectionMultiple: "/collection-prices/multiple",
  productscheck: "/product/check-product",
  productReport: "/product/report-product",
  productCharacteristics: "/collection/internet-shop",
  clients: "/contact",
  login: "/auth/login",
  userMe: "/user/info/me",
  parties: "/partiya",
  dataLibrary: "/product",
  transfers: "/transfer",
  transferBasket:"/transfer/basket",
  broned: "/booking",
  upload: "/media-upload/single/avatar/avatar",
  filial: "/filial",
  payrolls: "/payrolls",
  payrollsChangeStatus: "/payrolls/change-status",
  payrollItems: "/payroll-items",
  dealer: "/filial/dealer",
  filialMakeReport: "/filial/maker-report",
  filialReport: "/filial-report",
  qrBase: "/qr-base",
  cashflow: "/cashflow",
  cashflowTypes: "/cashflow-types",
  cashflowFilial :'/cashflow/for/filial-manager',
  openKassa: "/kassa/open-kassa",
  qrBaseCode: "/qr-base/find-by",
  order: "/order",
  orderBusket: "/order-basket",
  orderByKassa: "/order/order-by-kassa",
  orderBusketMultiple:'/order-basket/multiple',
  notes: "/notes",
  qrCodes: "/qr-codes",
  kassaReport: "/kassa/report",
  kassaReports:'/kassa-reports',
  kassaReportTotal:'/kassa-reports/total',
  kassa: "/kassa",
  kassaClose: "/kassa/close-kassa",
  statement: "/statement",
  productRemaining: "/product/remaining-products",
  productRemainingCollection:'/product/remaining-products-collection',
  excelProducts:'/excel/products',
  excelProduct:'/excel/product'
} as const;
