export const apiRoutes = {
  aboutUs: "/aboutus",
  report: "/report",
  user: "/user",
  userManagersAccountants: "/user/managers-accountants",
  userLog: "/user-time-log",
  userLoginGenerate: "/user/generate/login-user",
  crops: "/crops",
  products: "/product",
  orderBasketBookings:'/order-basket/bookings',
  productsIManager: "/product/internet-shop",
  collection: "/collection/remaining-collections",
  collectionProducts: "/collection/remaining-products",
  collectionPrice: "/collection-prices",
  collectionMultiple: "/collection-prices/multiple",
  productscheck: "/product/check-product",
  productReport: "/product/report-product",
  productCharacteristics: "/collection/internet-shop",
  clients: "/client",
  login: "/auth/login",
  userMe: "/user/info/me",
  parties: "/partiya",
  partiesChanngeStatus: "partiya/change-to",
  dataLibrary: "/product",
  transfers: "/transfer",
  transferReject:'/transfer/reject',
  transferBasket:"/transfer/basket",
  broned: "/booking",
  upload: "/media-upload/single/avatar/avatar",
  filial: "/filial",
  filialWarehouse: "/filial/warehouse-and-filial",
  payrolls: "/payrolls",
  payrollsChangeStatus: "/payrolls/change-status",
  payrollItems: "/payroll-items",
  dealer: "/filial/dealer",
  filialMakeReport: "/filial/maker-report",
  filialReport: "/filial-report",
  qrBase: "/qr-base",
  cashflow: "/cashflow",
  cashflowForMainManager:'/cashflow/for/main-manager',
  cashflowTypes: "/cashflow-types",
  cashflowFilial :'/cashflow/for/filial-manager',
  openKassa: "/kassa/open-kassa",
  qrBaseCode: "/qr-base/find-by",
  order: "/order",
  orderBusket: "/order-basket",
  orderByKassa: "/order/order-by-kassa",
  orderBusketMultiple:'/order-basket/multiple',
  notes: "/notes",
  qrCodes: "/qr-codes",
  kassaReport: "/kassa/report",
  kassaReports:'/kassa-reports',
  kassaReportTotal:'/kassa-reports/total',
  kassa: "/kassa",
  kassaClose: "/kassa/close-kassa",
  kassaCancel: "/kassa/cancel-kassa",
  statement: "/statement",
  productRemaining: "/product/remaining-products",
  countryReport:'/country-report',
  excelProducts:'/excel/products',
  excelProduct:'/excel/product',
  reports:"/reports",
  reportsDealer:'/reports/dealer-closed-by-d',
  sellerReports:'/seller-reports',
  sellerReportsMothly:'/seller-reports/monthly-report',
  sellerReportsItem:'/seller-reports-item/orders-by-date-range',
  excelCollection:'/excel/collection',
  excelProductsReport:'/excel/products/report',
  debt:"/debt",
  transferAccept:"/transfer/accept",
  clientDebtTotal:'/client/debt/total',
  clientDebtsByFilial:'/client/debts/by-filial',
  excelSingle:"/excel/single",
  factoryReport:'/factory-report',
  collectionReport:'/collection-report',
  productRemainingCollection:'/product/remaining-products-collection',
} as const;
