export const apiRoutes = {
  aboutUs: "/aboutus",
  user: "/user",
  crops: "/crops",
  products: "/product",
  collection: "/collection",
  collectionPrice: "/collection-prices",
  productscheck: "/product/check-product",
  productReport: "/product/report-product",
  login: "/auth/login",
  userMe: "/user/info/me",
  parties: "/product",
  dataLibrary: "/product",
  transfers: "/transfers",
  broned: "/booking",
  filial: "/filial",
  filialMakeReport: "/filial/maker-report",
  filialReport: "/filial-report",
  qrBase: "/qr-base",
  order: "/order",
  kassaOpen: `/kassa/open-kassa`,
  orderByKassa: "/order/order-by-kassa",
} as const;
