deploy:
  needs: build
  runs-on: ubuntu-latest
  steps:
    - name: Deploying to Docker server...
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd /home/user/getter/gilam-market-erp
          
          echo "Stashing and resetting repository..."
          git stash
          git reset --hard origin/main
          git clean -fd

          echo "Stopping and removing old container..."
          docker stop gilam-app || true
          docker rm gilam-app || true

          echo "Checking for any containers using port 80..."
          if docker ps | grep -q '80->80'; then
            echo "Port 80 is already in use by another container!"
            docker ps
            exit 1
          fi

          echo "Building new Docker image..."
          docker build -t gilam-app .

          echo "Starting new container..."
          docker run -d -p 80:80 --name gilam-app gilam-app