name: Deployment Grm Seller Web
on:
  push:
    branches:
      - oneip

jobs:
  build:
    runs-on: ubuntu-latest # Or other suitable runner environment
    strategy:
      matrix:
        node-version: [20] # Specify Node.js versions to test against

    steps:
      - uses: actions/checkout@v4 # Checkout your repository code

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10 Specify the pnpm version to install

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm' # Enable caching for pnpm dependencies

      - name: Install dependencies
        run: pnpm install

      - name: Build project (example)
        run: pnpm build

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploying to server...
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/oneip/grm-web
            git stash
            git pull origin oneip
            pnpm install
            pnpm run build
